# -*- coding: utf-8 -*-
"""CSC_120_Tic_Tac_Toe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vGTCzlLNMIo5yDnDvO-2VdwhfPBKHS65
"""

# This application creates a basic Tic Tac Toe game

# Create game board
board = []
board.append(['-', '-', '-'])
board.append(['-', '-', '-'])
board.append(['-', '-', '-'])

# Function to print each row of the game board
def print_board():
  for elem in board:
    print(elem)

print_board()